name: myTest
server:
  port: 8090
spring:
  datasource:
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: jdbc:mysql://127.0.0.1:3306/nextdemo_im
    username: root
    password: root
